name: Feature Request
description: Suggest a new sample or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new sample project or improvement to existing samples.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New Sample Project
        - Enhancement to Existing Sample
        - New Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: Detailed description of the feature or sample
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why is this valuable? What problem does it solve?
      placeholder: Explain the benefit to developers
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example or Reference
      description: Link to similar samples, tutorials, or documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
