name: Feature Request
description: Suggest a new sample or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature or sample
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Why is this useful?
      description: Explain the benefit
    validations:
      required: true
